export const logintypes = {
    CREATE_USER: "CREATE_USER",
    USER_LOGIN: "USER_LOGIN",
    USER_LOGOUT: "USER_LOGOUT",
    Login_GOOLE: "LOGIN_GOOLE",
    UPDATE_LOCATION: "UPDATE_LOCATION",
    RECENT_SEARCH: "RECENT_SEARCH",
    UPDATE_ORDERS: "UPDATE_ORDERS",
    TOGGLE_ERROR: "TOGGLE_ERROR",
};

export const loadingTypes = {
    TOOGGLE_LOADING: "TOOGGLE_LOADING",
};

export const restaurantsTypes = {
    CREATE_RESTAURANT: "CREATE_RESTAURANT",
    GET_RESTAURANT: "GET_RESTAURANT",
    FILTER_TYPE: "FILTER_TYPE",
    TOGGLE_LOADING: "TOGGLE_LOADING",
    GET_MENU: "GET_MENU",
};
